### ISSUE TITLE
No entities detected by the add-on

### ISSUE THREAD

**Issue by bistek22** [aquette/addon-smartnut#1]
# Problem

Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2 

It sounds like you've configured everything as needed, there are no errors in the logs, the UPS has been detected, the add-on has connected to Mosquitto, but you're unable to find the entities it detected. You've tried both automatic and manual configuration tests, but nothing seems to be adding.

![Zrzut ekranu 2023-12-29 150608](https://github.com/aquette/addon-smartnut/assets/72106904/b4632c6b-5339-4da5-9c96-8d6fdcf2dda3)

**Comment by aquette** [comment]
Hi @bistek22 
Thanks for testing the SmartNUT addon.
For now, it still publishes on mqtt topics not aligned with Home Assistant to be automatically detected (Sensor...).
That's my next step, after the end of year break.
Thanks again for your report and your patience

**Comment by bistek22** [comment]
I'm waiting for further development of the project, it looks very promising, finally I'll be able to manage my servers safely and easily with Bee.

**Comment by aquette** [comment]
Thanks for your encouraging feedback 😄
What is Bee by the way? I'm just a month old into home assistant...

**Comment by aquette** [comment]
Just a heads up, I'm still heavily over busy with work and home
