### ISSUE TITLE
Too much CPU usage

### ISSUE THREAD

**Issue by picotouch** [aquette/addon-smartnut#3]
# Problem/Motivation

I installed the addon on HA on Proxmox. 
CPU load by addon is extremely high (20-30%).
The addon works, the UPS is recognized, messages arrive in MQTT.

**Comment by aquette** [comment]
Thanks a lot for testing @picotouch 😃

The CPU level is indeed definitely too high compared to what it should be!
It's part of the next topics, with the right mqtt publication too. Drivers instability is also something I noted (s6 containers et unix socket related I assume

Those will be addressed by the native implementation for sure. But I'm not sure I'll be able to improve much the present prototype / hack.
